chore: `k8s`, and `cluster` partial refactor
zarf-dev/zarf pull request #2271
Opened 2024-01-30 17:20 UTC by chrishorton

## Description

Refactor `k8s` and `cluster` packages to consolidate `GetImagesWithNodes` and `GetAllImages` into one function `GetAvailableImagesFromNodes`.

Move utility functions from `images.go` to `prepare.go` where they are used.

Delete `images.go`

## Related Issue

Fixes #2222

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Other (security config, docs update, etc)

## Checklist before merging

- [x] Test, docs, adr added or updated as needed
- [x] [Contributor Guide Steps](https://github.com/defenseunicorns/zarf/blob/main/CONTRIBUTING.md#developer-workflow) followed

2024-01-30 17:22 UTC, chrishorton commented
Should `GetImagesFromAvailableNodes` and `ImageNodeMap` be public?

2024-01-30 22:17 UTC, Racer159 requested changes
Overall looks good! And yes I think they should be private for now to simplify the public interface.  Thinking more, I also suggested a more descriptive name for the function since it is so injector specific

2024-01-30 22:17 UTC, Racer159 commented on src/pkg/cluster/injector.go
> +func (c *Cluster) GetImagesFromAvailableNodes(timeoutDuration time.Duration) (ImageNodeMap, error) {
```suggestion
func (c *Cluster) getImagesAndNodesForInjection(timeoutDuration time.Duration) (imageNodeMap, error) {
```

2024-01-30 22:17 UTC, Racer159 commented on src/pkg/cluster/injector.go
> +	var images ImageNodeMap
```suggestion
	var images imageNodeMap
```

2024-01-30 22:17 UTC, Racer159 commented on src/pkg/cluster/injector.go
> +type ImageNodeMap map[string][]string
```suggestion
type imageNodeMap map[string][]string
```

2024-01-31 02:49 UTC, Racer159 requested changes

2024-01-31 02:49 UTC, Racer159 commented on src/pkg/cluster/injector.go
> +	if images, err = c.GetImagesFromAvailableNodes(timeout); err != nil {
```suggestion
	if images, err = c.getImagesAndNodesForInjection(timeout); err != nil {
```
This also has to change

2024-02-07 22:31 UTC, Racer159 approved these changes
lgtm

2024-02-07 22:45 UTC, Noxsios approved these changes

2024-02-07 22:45 UTC, merged