chore: add release template & update contributing
zarf-dev/zarf pull request #2486
Opened 2024-05-08 19:48 UTC by schristoff-du

2024-05-09 06:43 UTC, lucasrod16 approved these changes
LGTM

2024-05-23 23:09 UTC, lucasrod16 requested changes

2024-05-23 23:09 UTC, lucasrod16 commented on .github/ISSUE_TEMPLATE/release.md
> +Release checklist:
We should add merging the `goreleaser` PR in the [homebrew-tap](https://github.com/defenseunicorns/homebrew-tap) repo as a step in the release checklist

2024-05-23 23:18 UTC, lucasrod16 requested changes

2024-05-23 23:18 UTC, lucasrod16 commented on .github/ISSUE_TEMPLATE/release.md
> +[ ] `git tag -sa $RELEASE_VERSION -m "$RELEASE_VERSION" `
Would be good to note that the tag has to be pushed to remote:

```shell
git push origin "$RELEASE_VERSION"
```

2024-06-18 12:52 UTC, AustinAbro321 requested changes

2024-06-18 12:52 UTC, AustinAbro321 commented on .github/ISSUE_TEMPLATE/release.md
> +[ ] Send release update in the #zarf Kubernetes Channel
We should add an item to this checklist to merge the PR goreleaser creates on the [homebrew-tap repo](https://github.com/defenseunicorns/homebrew-tap)

2024-11-07 20:43 UTC, closed without merging