docs: update repo name across docs
zarf-dev/zarf pull request #2735
Opened 2024-07-18 15:30 UTC by salaxander

## Description
May have missed some, but it does look like there are some that need to stay as is

2024-07-19 16:47 UTC, AustinAbro321 requested changes

2024-07-19 16:47 UTC, AustinAbro321 commented on site/src/content/docs/ref/github-action.mdx
> +The [setup-zarf](https://github.com/zarf-dev/setup-zarf) Github action is an officially supported action to install any version of Zarf and it's `init` package with zero added dependencies.
This action hasn't been moved yet

2024-07-19 16:47 UTC, AustinAbro321 commented on site/src/content/docs/ref/github-action.mdx
> +        uses: zarf-dev/setup-zarf@main # use action's main branch
ditto

2024-07-19 16:47 UTC, AustinAbro321 commented on site/src/content/docs/ref/github-action.mdx
> +More examples are located in the action's [README.md](https://github.com/zarf-dev/setup-zarf#readme)
ditto

2024-07-19 17:31 UTC, phillebaba commented on site/src/content/docs/faq.mdx
> +Zarf was built by the developers at [Defense Unicorns](https://www.zarf-dev.com/) and an amazing community of contributors.
zarf-dev.com also needs to function properly first.

2024-07-19 17:36 UTC, phillebaba commented on site/src/content/docs/commands/zarf_package_pull.md
> -$ zarf package pull oci://ghcr.io/defenseunicorns/packages/dos-games:1.0.0
This has not been moved.

2024-07-23 13:38 UTC, salaxander commented on site/src/content/docs/faq.mdx
> +Zarf was built by the developers at [Defense Unicorns](https://www.zarf-dev.com/) and an amazing community of contributors.
Oh my bad, this should be discarded

2024-07-24 14:49 UTC, AustinAbro321 commented on site/src/content/docs/ref/deploy.mdx
> +You can also specify a package locally, or via oci such as `zarf package deploy oci://zarf-dev/dos-games:1.0.0-$(uname -m) --key=https://zarf.dev/cosign.pub`
This should stay the same, but this is the package not the image so it's actually hosted on the defense unicorn github

2024-07-24 14:51 UTC, AustinAbro321 commented on site/src/content/docs/ref/deploy.mdx
> +You can also specify a package locally, or via oci such as `zarf package deploy oci://zarf-dev/dos-games:1.0.0-$(uname -m) --key=https://zarf.dev/cosign.pub`
```suggestion
You can also specify a package locally, or via oci such as `zarf package deploy oci://defenseunicorns/dos-games:1.0.0 --key=https://zarf.dev/cosign.pub`
```
though we should delete the uname as we no longer append arch to our oci packages

2024-07-24 14:52 UTC, AustinAbro321 commented on site/src/content/docs/tutorials/3-deploy-a-retro-arcade.mdx
> +1. The `dos-games` package is easily deployable via `oci://` by running `zarf package deploy oci://zarf-dev/dos-games:1.0.0-$(uname -m) --key=https://zarf.dev/cosign.pub`.
```suggestion
1. The `dos-games` package is easily deployable via `oci://` by running `zarf package deploy oci://defenseunicorns/dos-games:1.0.0 --key=https://zarf.dev/cosign.pub`.
```

2024-07-24 22:59 UTC, schristoff approved these changes

2024-07-25 08:22 UTC, phillebaba approved these changes

2024-07-25 09:16 UTC, merged