refactor: FindImages to return errors immediatly
zarf-dev/zarf pull request #2851
Opened 2024-08-07 14:45 UTC by phillebaba

## Description

This removes warning logs and replaces it with returning the errors immediatly.

## Related Issue

Relates to #2849 

## Checklist before merging

- [ ] Test, docs, adr added or updated as needed
- [ ] [Contributor Guide Steps](https://github.com/zarf-dev/zarf/blob/main/CONTRIBUTING.md#developer-workflow) followed

2024-08-07 19:44 UTC, schristoff requested changes
If you could update the existing unit test in `prepare_test.go` to cover the new functionality where we no longer will continue if we have an error in the charts or cosignlookups that would be very helpful.

2024-08-14 06:01 UTC, schristoff requested changes
great job!

2024-08-14 08:43 UTC, phillebaba commented on src/pkg/packager/prepare_test.go
> +				require.ElementsMatch(t, v, images[k])
We use require everywhere else. Require will exit immediately while assert will not. I prefer immediately exiting when a check fails.

2024-08-14 12:37 UTC, schristoff approved these changes

2024-08-14 19:45 UTC, merged