Data retry
zarf-dev/zarf pull request #2867
Opened 2024-08-12 09:24 UTC by phillebaba

## Description

This change removes the retrying in data injections, as it does not have any effect. The current implementation will only retry at a single condition which is when the pods returned from the wait function is empty.

https://github.com/zarf-dev/zarf/blob/0943d76b25464ab7ad948b4c93957b22d966c02b/src/pkg/cluster/data.go#L88-L90

This event wont actually happen because the wait logic will run until the context cancelled if the pod list is empty. This means that returning an empty list is impossible.

Removing the nested retry implementation increases legibility. 

## Related Issue

Depends on #2856

## Checklist before merging

- [ ] Test, docs, adr added or updated as needed
- [ ] [Contributor Guide Steps](https://github.com/zarf-dev/zarf/blob/main/CONTRIBUTING.md#developer-workflow) followed

2024-08-13 20:23 UTC, AustinAbro321 approved these changes

2024-08-13 21:51 UTC, schristoff requested changes
tests please 
![](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExMDZqbjhvY2c3ZTVyd3N3dXA2Ymp3dWthNjMyaHBmbGdvdno1bDAzbSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/8abAbOrQ9rvLG/giphy.gif)

2024-08-14 11:30 UTC, phillebaba commented
The data injection can not be tested in its current state as it is shelling out to both tar and kubectl. What exactly should be tested here maybe other than `waitForPodsAndContainers` ?

2024-08-14 19:27 UTC, schristoff commented
Yeah, upon re-review it will be too burdensome to try and write functional tests for `HandleDataInjection` without a major refactor of the functionality itself.

2024-08-14 19:27 UTC, schristoff approved these changes

2024-08-15 09:35 UTC, merged