refactor: break --insecure into --http-only and --tls-skip-verify
zarf-dev/zarf pull request #2936
Opened 2024-08-28 03:14 UTC by joonas

## Description

Attempting to break up the `--insecure` global flag into two separate flags, `--http-only` and `--tls-skip-verify`, that are hopefully easier to understand.

It wasn't immediately obvious how the the following 2 instances of the flag being deprecated should be addressed:
1. https://github.com/zarf-dev/zarf/blob/d7eb999851bc20ac68155fe11a23ed2b151a975d/src/pkg/packager/sources/url.go#L33-L37
2. https://github.com/zarf-dev/zarf/blob/d7eb999851bc20ac68155fe11a23ed2b151a975d/src/pkg/packager/sources/validate.go#L31-L36

## Related Issue

Fixes #2860

Relates to #

## Checklist before merging

- [ ] Test, docs, adr added or updated as needed
- [ ] [Contributor Guide Steps](https://github.com/zarf-dev/zarf/blob/main/CONTRIBUTING.md#developer-workflow) followed

2024-08-28 18:12 UTC, AustinAbro321 commented
Great question, unfortunately the `insecure` flag is pretty overloaded. I think it'll be better to just create two more flags to replace it's behavior

For this block, add a flag called `--insecure-no-shasum` to just the `zarf package pull` command [zarf/src/pkg/packager/sources/url.go](https://github.com/zarf-dev/zarf/blob/d7eb999851bc20ac68155fe11a23ed2b151a975d/src/pkg/packager/sources/url.go#L33-L37)

For this block, add a flag called `--insecure-no-signature-validation` to the `zarf package` command [zarf/src/pkg/packager/sources/validate.go](https://github.com/zarf-dev/zarf/blob/d7eb999851bc20ac68155fe11a23ed2b151a975d/src/pkg/packager/sources/validate.go#L31-L36)

You can add these new fields to the types.ZarfPackageOptions struct

2024-08-28 18:18 UTC, AustinAbro321 requested changes
Great start, left some feedback. Could you also replace the uses of `--insecure` in the test suite. Leave one use of `--insecure` for each new flag so we can test that the flag still works though deprecated.

2024-08-28 18:18 UTC, AustinAbro321 commented on src/cmd/root.go
> +	rootCmd.PersistentFlags().BoolVar(&config.CommonOptions.HttpOnly, "http-only", v.GetBool(common.VHttpOnly), lang.RootCmdFlagHttpOnly)
I know this is not what I put in the issue, but lets call this `plain-http`, I think it sounds a bit better and it's what helm uses for the same purpose.

2024-08-29 04:46 UTC, joonas commented on src/cmd/root.go
> +	rootCmd.PersistentFlags().MarkHidden("insecure")
Makes sense, adopted `MarkDeprecated` and your language suggestion

2024-08-29 05:27 UTC, joonas commented on src/config/config.go
> +	return CommonOptions.HttpOnly || CommonOptions.Insecure
Great callout, I hadn't considered that, but that's definitely a much cleaner way to handle this

2024-08-29 05:41 UTC, joonas commented
@AustinAbro321 appreciate all the feedback, I tried to make sure I addressed it diligently, but please let me know if I missed the mark somewhere.

I haven't yet had a chance to revisit the use of `--insecure` in the test suite, but on a cursory look across the tests that contain the flag I noticed there's probably a combination of the above flag changes should be applied.

My plan for how I was going to address the tests is as follows:

1. Where `--insecure` is being replaced with `--insecure-skip-tls-verify` and `--plain-http`, replace the `--insecure` flag with both of those in each case
2. Where `--insecure` is being replaced with `--insecure-no-signature-validation`, apply that across the impacted examples
3. Where `--insecure` is being replaced with `--insecure-no-shasum`, apply that across the impacted examples

Does that roughly line up with what you had in mind?

2024-08-29 07:59 UTC, phillebaba commented
Some comments about this change. First of all we should stop adding things to the whole lang package as it is something that should be removed. Second of all I don't see the point of adding an "insecure" prefix to all of these flags. I am fine with `--insecure-skip-tls-verify` and `--plain-http` as they are common in other projects. The other two flags should be called something else or not exist at all. I suggest renaming `--insecure-no-signature-validation` to `--skip-signature-validation`.

I don't see a point of being able to disable digest verification while pulling? Why would you event wan't to do that? It could also result in confusion for users in the future who assume that a package pulled has the expected digest.

2024-08-29 16:11 UTC, AustinAbro321 commented
Yeah that looks like a solid strategy for changing the flag in tests @joonas 

Good point @phillebaba, I doubt anyone is relying on the insecure feature for `zarf package pull` and if they are they shouldn't be. I also like `--skip-signature-validation` better

2024-09-01 22:54 UTC, joonas commented
I believe I've now addressed all of test cases and instances of where the flags were used 🙂

2024-09-03 07:33 UTC, phillebaba requested changes
Looks good I

2024-09-03 08:02 UTC, phillebaba commented
@joonas I have verified that setting a pre run function in a sub command disables the root pre run. Which would explain why the tests are currently failing.

2024-09-04 02:29 UTC, joonas commented
> @joonas I have verified that setting a pre run function in a sub command disables the root pre run. Which would explain why the tests are currently failing.

Ah, it looks like to enable this behavior, the [`EnableTraverseRunHooks` variable](https://pkg.go.dev/github.com/spf13/cobra#pkg-variables) introduced in https://github.com/spf13/cobra/pull/2044 needs to be set to `true`.

Does that seem like a reasonable change to make, or would you rather have the logic for setting `pkgConfig.PkgOpts.SkipSignatureValidation` to true if `config.CommonOptions.Insecure` is set to true copied to each sub command under the package command where it might be used?

I'm fine to go either way if changing the global flag in Cobra seems like too much of a behavior change to resolve this.

2024-09-04 09:52 UTC, phillebaba commented
Looks like my comments about the pre run functions did not make it with my review. Or I cant find it anymore.

In it I shared that I was unsure about enabling `EnableTraverseRunHooks` due to it being a global variable. My first thought when finding the same issue that you did a while back was to enable it. However because Zarf embeds other commands it makes me unsure if this would cause unexpected behavior in these tools.

In the end we probably want to get away from the shared package options struct which is currently in use. My other suggestion would be to put it in the root pre run function. Thinking about it now I would prefer the code duplication over that option.

2024-09-07 04:44 UTC, joonas commented
@AustinAbro321 @phillebaba I finally had a chance to go back and fix the one e2e test that was failing due to the help text changes.

I've also re-generated the command docs pages to incorporate the flag changes and I went ahead and rebased on top of the latest changes (as of Friday evening)

This should hopefully be all that's needed to have the test suite now pass with flying colors 🙂

2024-09-10 16:00 UTC, AustinAbro321 requested changes
It's close, requested a few more changes. Thank you for taking this on.

2024-09-11 00:57 UTC, joonas commented on src/test/e2e/11_oci_pull_inspect_test.go
> +	stdOut, stdErr, err = e2e.Zarf(suite.T(), "package", "pull", "oci://"+badPullInspectRef.String(), "--plain-http", "--insecure-skip-tls-verify")
done!

2024-09-11 00:57 UTC, joonas commented on src/test/e2e/11_oci_pull_inspect_test.go
> +	_, stdErr, err := e2e.Zarf(suite.T(), "package", "inspect", "oci://"+badPullInspectRef.String(), "--plain-http", "--insecure-skip-tls-verify", "--skip-signature-validation")
done!

2024-09-11 00:57 UTC, joonas commented on src/cmd/package.go
done!

2024-09-13 19:43 UTC, phillebaba approved these changes
LGTM

2024-09-13 20:06 UTC, merged