fix: imported helm overrides
zarf-dev/zarf pull request #2967
Opened 2024-09-04 21:11 UTC by rjferguson21

## Description
Ensures imported components merge Helm override variables, similar to the existing behavior with `valueFiles`.

## Related Issue
Fixes https://github.com/zarf-dev/zarf/issues/2966

## Checklist before merging

- [ ] Test, docs, adr added or updated as needed
- [ ] [Contributor Guide Steps](https://github.com/zarf-dev/zarf/blob/main/CONTRIBUTING.md#developer-workflow) followed

2024-09-05 18:23 UTC, AustinAbro321 requested changes
Thanks for making this! This not already being a feature is an oversight

2024-09-05 19:08 UTC, rjferguson21 commented on src/pkg/packager/composer/override.go
> +				c.Charts[idx].Variables = append(c.Charts[idx].Variables, overrideChart.Variables...)
Updated to include a test for chart variables.  Included chart variables in `createDummyComponent` function, but would be happy to split it up into a totally separate test.

2024-09-05 19:10 UTC, rjferguson21 commented on src/test/packages/09-composable-packages/zarf.yaml
> +        variables:
With the addition of the unit test, should I remove the inclusion of the e2e test?

2024-09-05 21:44 UTC, AustinAbro321 commented on src/pkg/packager/composer/override.go
> +				c.Charts[idx].Variables = append(c.Charts[idx].Variables, overrideChart.Variables...)
It's good where it is thanks!

2024-09-05 21:45 UTC, AustinAbro321 commented on src/test/packages/09-composable-packages/zarf.yaml
> +        variables:
Yes

2024-09-05 22:22 UTC, rjferguson21 commented on src/test/packages/09-composable-packages/zarf.yaml
> +        variables:
Updated to remove the e2e test

2024-09-06 15:39 UTC, AustinAbro321 approved these changes
LGTM

2024-09-06 16:34 UTC, merged