Fix  repository.go
zarf-dev/zarf pull request #2996
Opened 2024-09-14 12:49 UTC by ittacco

fix: Clone of Azure devops git repo not working with private repositories

Refs: #2994

## Description
Added return in case the Repository is correctly cloned by gitCloneFallback

## Related Issue

Fixes #2994

## Checklist before merging

- [ ] Test, docs, adr added or updated as needed
- [ ] [Contributor Guide Steps](https://github.com/zarf-dev/zarf/blob/main/CONTRIBUTING.md#developer-workflow) followed

2024-09-14 22:58 UTC, phillebaba requested changes
This is interesting, I wonder if this is a regression from the error work that has been done or if this has always been here?

Not sure if this is easily testable but could be worth it to avoid regression.

2024-09-14 22:58 UTC, phillebaba commented on src/internal/git/repository.go
> +		} else {
```suggestion
		} 
		return r, nil
```

2024-10-18 16:50 UTC, ittacco commented on src/internal/git/repository.go
> +		} else {
fixed syntax

2024-11-07 20:48 UTC, schristoff commented
Hey! Could you please sign DCO so we can get this merged? :)

2024-11-09 09:38 UTC, ittacco commented
Hi @schristoff , I hope DCO are ok now!

2024-11-19 17:14 UTC, AustinAbro321 commented
@ittacco Hey looks like something went wrong when you did DCO, it's currently showing 240 files changed. Could you reset this PR, I know it was originally a couple line change. If you `git reset main` then re add your changes, sign your commit and force push it should work.

2025-07-08 16:35 UTC, joaofasilva-kitar commented
@brandtkeller any change to get this merged? seems to be blocking the usage of azure devops repos

2025-07-14 18:45 UTC, brandtkeller commented
@joaofasilva-kitar  I agree - let's get this over the line.

@ittacco I believe it looks good - I don't want to update your branch/fork for you in the event there is still future work to do. So if you can get this branch up-to-date we can get it tested and over the finish line!

2025-08-21 17:00 UTC, joaocc commented
Hi everyone! Any updates on getting this merged/deployed? Thanks and have a great vacation period!

2025-09-16 16:53 UTC, brandtkeller commented
This change in isolation appears to result in some failing tests - @joaocc I will see if I can find some cycles to look at the results of testing and identify a path forward.

2025-09-16 22:42 UTC, brandtkeller commented
Incorporated the intent of this change plus some enhancements into #4186 - which as subsequently been merged. 

CC: @joaocc @joaofasilva-kitar

2025-09-16 22:42 UTC, closed without merging