feature: Add ability for zarf to find oci artifacts for fluxcd ocirepo resource
zarf-dev/zarf pull request #3238
Opened 2024-11-13 17:53 UTC by a1994sc

## Description

When trying to discover images with the `OCIRepositry` kind from FluxCD, `zarf` did not have logic for finding them with `zarf dev find-images`

## Checklist before merging

- [x] Test, docs, adr added or updated as needed
- [x] [Contributor Guide Steps](https://github.com/zarf-dev/zarf/blob/main/CONTRIBUTING.md#developer-workflow) followed

2024-11-20 21:36 UTC, a1994sc commented
Fixes #3255

2024-11-26 08:25 UTC, phillebaba commented
As with #3236 we are currently refactoring findImages so it will be hard to take this PR at this moment.

2024-11-26 11:23 UTC, a1994sc commented
OK, that works for me @phillebaba, thank you very much.

2025-04-11 12:03 UTC, AustinAbro321 commented
@a1994sc Now that find images is refactored, would you be willing to recreate this PR in [the new implementation](https://github.com/zarf-dev/zarf/blob/main/src/internal/packager2/find_images.go)

2025-04-11 14:21 UTC, a1994sc commented
Updated the PR

2025-04-11 16:19 UTC, AustinAbro321 requested changes
small comments, otherwise looks good. Nice work!

2025-04-11 16:19 UTC, AustinAbro321 commented on src/internal/packager2/find_images.go
> +		fmt.Errorf("Can not use semver or semverFilter with OCIRepository")
```suggestion
		logger.From(ctx).Error("can not use semver or semverFilter with OCIRepository")
```
Pass context here and use the builtin logger

2025-04-11 16:19 UTC, AustinAbro321 commented on src/internal/packager2/find_images.go
> +	s.Write([]byte(t[1]))
According to the flux docs the `oci://` is required, so I think it'd be simpler to do a `strings.TrimPrefix` here https://fluxcd.io/flux/components/source/ocirepositories/#url

2025-04-11 19:19 UTC, a1994sc commented on src/internal/packager2/find_images.go
> +		fmt.Errorf("Can not use semver or semverFilter with OCIRepository")
Updated per comment

2025-04-11 19:20 UTC, a1994sc commented on src/internal/packager2/find_images.go
> +	s.Write([]byte(t[1]))
Updated the logic to use the `strings.TrimPrefix` func

2025-04-11 19:21 UTC, a1994sc commented on src/internal/packager2/find_images_test.go
> +					Matches:       []string{},
Not sure that I handled this error correctly... I tried setting a `expectedErr:` but it didn't seem to pass... so any input would be very grateful

2025-04-14 13:05 UTC, AustinAbro321 commented on src/internal/packager2/find_images_test.go
> +					Matches:       []string{},
Yeah `expectErr` won't work, because we're not returning an error when we run into the semver check just logging, which makes sense, given that we want the rest of find-images to run in this case. IMO just delete this test case.

2025-04-14 13:16 UTC, AustinAbro321 commented on src/internal/packager2/find_images.go
> +		logger.From(ctx).Error("can not use semver or semverFilter with OCIRepository")
We should use the `Warn` function rather than the `Error` function. We should also give users the image url, and oci repository name so they can easily find it. (note: you'll have to pass in `sourcev1beta2.OCIRepository` for this) 
```suggestion
		logger.From(ctx).Warn("cannot create image reference with semver or semverFilter", "image", url, "OCIRepository", repo.Name)
```

2025-04-14 16:12 UTC, a1994sc commented on src/internal/packager2/find_images.go
> +		logger.From(ctx).Error("can not use semver or semverFilter with OCIRepository")
![image](https://github.com/user-attachments/assets/b13deff6-e22a-41ce-8afb-3f085df1d14a)

2025-04-14 16:12 UTC, a1994sc commented on src/internal/packager2/find_images.go
> +		logger.From(ctx).Error("can not use semver or semverFilter with OCIRepository")
Updated PR with your comments Austin

2025-04-14 18:57 UTC, AustinAbro321 requested changes
Just remove the `flux-oci-repo-semver` directory and I will approve

2025-04-16 17:16 UTC, AustinAbro321 commented
@a1994sc Running tests right now and if everything passes I'll approve. FYI we use a GitHub feature called merge queue which runs all tests against this branch with main merged into it before the actual merge happens, so no worries if your branch is not up to date.

2025-04-17 13:28 UTC, AustinAbro321 approved these changes

2025-04-17 15:59 UTC, mkcp approved these changes

2025-04-17 16:27 UTC, merged